# Generated by Django 3.1.5 on 2021-02-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_mod', '0003_author_blog_entry_remoteapiaccount'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='remoteapiaccount',
            constraint=models.CheckConstraint(check=models.Q(id=1), name='test_mod_remoteapiaccount_single_instance'),
        ),
    ]
