# Generated by Django 3.0.7 on 2020-06-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_like_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
