# Generated by Django 2.1 on 2020-05-28 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.IntegerField(choices=[(0, 'Hamburger'), (1, 'Pancake')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ingridients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese', models.IntegerField(default=0)),
                ('ham', models.IntegerField(default=0)),
                ('onion', models.IntegerField(default=0)),
                ('bread', models.IntegerField(default=0)),
                ('ketchup', models.IntegerField(default=0)),
                ('milk', models.IntegerField(default=0)),
                ('butter', models.IntegerField(default=0)),
                ('honey', models.IntegerField(default=0)),
                ('eggs', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='cookbook',
            name='ingridients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.Ingridients'),
        ),
    ]
