# Generated by Django 2.1 on 2020-05-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbook',
            name='ingridients',
            field=models.CharField(max_length=1024),
        ),
        migrations.DeleteModel(
            name='Ingridients',
        ),
    ]
